# configs/fedbabu.yaml

algo: fedbabu

dataset: cifar10 # Options: cifar10, cifar20, cifar100, retina

partition: dir # Options: dir, shards

dir_alpha: 0.3 # Dirichlet distribution parameter for data partitioning
num_shards: 5 # Number of shards for each client

model: resnet # Options: lenetgn, resnet

ablation_feature_shift: false # If true, use the ablation with feature shift for FedDRM
shift_level: high # Options: low, mid, high

ablation_arch: false # If true, use the ablation architecture for FedDRM
share_level: deep # Options: no_share, shallow, mid, deep

sensitivity_num_clients: false # If true, use the ablation with varying num_clients for FedDRM
num_clients: 8 # Number of clients

# ---------------------------------------------------------------------------------------

device: cuda:0

seed: 2025

commu_round: 800
ft_round: 200
local_steps: 10
batch_size: 128
lr: 0.01
momentum: 0.9
weight_decay: 5e-4
